version: "3.8"
services:
  app:
    build:
      args:
        user: joinme
        uid: 1000
      context: ./
      dockerfile: ./docker-compose/joinme-app/joinme-app.dockerfile
    image: joinme-app
    container_name: joinme-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./joinme:/var/www
    networks:
      - joinme

  db:
    image: mysql:8.0
    container_name: joinme-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/joinme-db:/docker-entrypoint-initdb.d
    networks:
      - joinme
  nginx:
    image: nginx:1.17-alpine
    container_name: joinme-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./joinme:/var/www
      - ./docker-compose/joinme-nginx:/etc/nginx/conf.d
    networks:
      - joinme
networks:
  joinme:
    driver: bridge
